FC = gfortran
SRC = $(wildcard *.f90)
OBJ = $(SRC:.f90=.o)
EXEC = my_program

run: my_program
	./my_program

.PHONY: all run

all: $(EXEC)

$(EXEC): $(OBJ)
	$(FC) -o $@ $^ -Wall

%.o: %.f90
	$(FC) -c -o $@ $<

clean:
	rm -f $(OBJ) $(EXEC)
